/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TesterrorRouteImport } from './routes/testerror'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TaskTaskIdRouteImport } from './routes/task/$taskId'

const TesterrorRoute = TesterrorRouteImport.update({
  id: '/testerror',
  path: '/testerror',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TaskTaskIdRoute = TaskTaskIdRouteImport.update({
  id: '/task/$taskId',
  path: '/task/$taskId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/testerror': typeof TesterrorRoute
  '/task/$taskId': typeof TaskTaskIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/testerror': typeof TesterrorRoute
  '/task/$taskId': typeof TaskTaskIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/testerror': typeof TesterrorRoute
  '/task/$taskId': typeof TaskTaskIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/testerror' | '/task/$taskId'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/testerror' | '/task/$taskId'
  id: '__root__' | '/' | '/testerror' | '/task/$taskId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  TesterrorRoute: typeof TesterrorRoute
  TaskTaskIdRoute: typeof TaskTaskIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testerror': {
      id: '/testerror'
      path: '/testerror'
      fullPath: '/testerror'
      preLoaderRoute: typeof TesterrorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/task/$taskId': {
      id: '/task/$taskId'
      path: '/task/$taskId'
      fullPath: '/task/$taskId'
      preLoaderRoute: typeof TaskTaskIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  TesterrorRoute: TesterrorRoute,
  TaskTaskIdRoute: TaskTaskIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
